services:
  app:
    build:
      context: backend
      dockerfile: backend/Dockerfile
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - app
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - app
    volumes:
      - mongo_data:/etc/mongo
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/var/www
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    networks:
      - app

volumes:
  mongo_data:

networks:
  app:
